apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sanic
  labels:
    app: sanic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sanic
  template:
    metadata:
      labels:
        app: sanic
    spec:
      containers:
      - name: sanic
        image: my_sanic
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1
          requests:
            memory: 64Mi
            cpu: 0.05
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: sanic
spec:
  type: NodePort
  selector:
    app: sanic
  ports:
  - name: server
    port: 8000
    targetPort: 8000
