# === CONSUL ==========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: consul
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8500

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: consul
spec:
  type: NodePort
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
