apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    cattle.io/creator: norman
    objectset.rio.cattle.io/hash: 10cb005ad0b66e97820b1672811ea7a1ff926b47
  name: coredns
  namespace: kube-system
