version: '3'
services:
  server:
    image: rancher/k3s:v0.2.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=kube
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - /tmp:/var/lib/rancher/k3s/agent/images
    - /tmp/manifests:/var/lib/rancher/k3s/server/manifests
    # This is just so that we get the kubeconfig file out
    - ~/.x123/:/output
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.2.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=kube
    volumes:
    - /tmp/images:/var/lib/rancher/k3s/agent/images
    - disk1:/k3s/volumes
    - /tmp/data:/data

volumes:
  k3s-server: {}
  disk1: {}
