version: '3'
services:
  server:
    image: rancher/k3s:v0.3.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=kube
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - /tmp/k3s/manifests:/var/lib/rancher/k3s/server/manifests
    # This is just so that we get the kubeconfig file out
    - ~/.x123/:/output
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.3.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=kube
    volumes:
    - /tmp/k3s/images:/var/lib/rancher/k3s/agent/images
    - /tmp/k3s/data:/data
    - disk1:/k3s/volumes/disk1
    #- disk2:/k3s/volumes/disk2
    #- disk3:/k3s/volumes/disk3
    #- disk4:/k3s/volumes/disk4
    #- disk5:/k3s/volumes/disk5
    #- disk6:/k3s/volumes/disk6
    #- disk7:/k3s/volumes/disk7
    #- disk8:/k3s/volumes/disk8
    #- disk9:/k3s/volumes/disk9
    #- disk10:/k3s/volumes/disk10
    #- disk11:/k3s/volumes/disk11
    #- disk12:/k3s/volumes/disk12
    #- disk13:/k3s/volumes/disk13
    #- disk14:/k3s/volumes/disk14
    #- disk15:/k3s/volumes/disk15
    #- disk16:/k3s/volumes/disk16
    #- disk17:/k3s/volumes/disk17
    #- disk18:/k3s/volumes/disk18
    #- disk19:/k3s/volumes/disk19
    #- disk20:/k3s/volumes/disk20

volumes:
  k3s-server: {}
  # TODO: we need to fix issue with Nfs to have dynamic allocation with only one disk
  disk1: {}
  #disk2: {}
  #disk3: {}
  #disk4: {}
  #disk5: {}
  #disk6: {}
  #disk7: {}
  #disk8: {}
  #disk9: {}
  #disk10: {}
  #disk11: {}
  #disk12: {}
  #isk13: {}
  #disk14: {}
  #disk15: {}
  #isk16: {}
  #isk17: {}
  #isk18: {}
  #disk19: {}
  #disk20: {}
