# === REDIS ==========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0.11-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 256Mi
            cpu: 0.2
          requests:
            memory: 128Mi
            cpu: 0.1

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
