apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-sanic
  labels:
    app: hello-sanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-sanic
  template:
    metadata:
      labels:
        app: hello-sanic
    spec:
      containers:
      - name: hello-sanic
        image: hello-sanic
        #imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1
          requests:
            memory: 64Mi
            cpu: 0.05
        readinessProbe:
          httpGet:
            #path: /health
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            #path: /health
            path: /
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: hello-sanic
spec:
  type: NodePort
  selector:
    app: hello-sanic
  ports:
  - name: server
    port: 8000
    targetPort: 8000
