apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: seeder-api
  labels:
    app: seeder-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seeder-api
  template:
    metadata:
      labels:
        app: seeder-api
    spec:
      containers:
      - name: seeder-api
        image: my_seeder
        imagePullPolicy: IfNotPresent
        env:
        - name: MQ_HOST
          value: rabbitmq
        - name: PYTHONUNBUFFERED
          value: '1'
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: seeder-api
spec:
  type: NodePort
  selector:
    app: seeder-api
  ports:
  - name: server
    port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: seeder-splitter-mqp
  labels:
    app: seeder-splitter-mqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder-splitter-mqp
  template:
    metadata:
      labels:
        app: seeder-splitter-mqp
    spec:
      containers:
      - name: seeder-splitter-mqp
        image: my_seeder
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["splitter_mqp.py"]
        env:
        - name: MQ_HOST
          value: rabbitmq
        - name: API_URL
          value: http://seeder-api:8000
        - name: PYTHONUNBUFFERED
          value: '1'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: seeder-transformer-mqp
  labels:
    app: seeder-transformer-mqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder-transformer-mqp
  template:
    metadata:
      labels:
        app: seeder-transformer-mqp
    spec:
      containers:
      - name: seeder-transformer-mqp
        image: my_seeder
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["transformer_mqp.py"]
        env:
        - name: MQ_HOST
          value: rabbitmq
        - name: PYTHONUNBUFFERED
          value: '1'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: seeder-mqp
  labels:
    app: seeder-mqp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seeder-mqp
  template:
    metadata:
      labels:
        app: seeder-mqp
    spec:
      containers:
      - name: seeder-mqp
        image: my_seeder
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["seeder_mqp.py"]
        env:
        - name: MQ_HOST
          value: rabbitmq
        - name: S_CONSUL_HOST
          value: consul
        - name: S_VAULT_HOST
          value: vault
        - name: S_VAULT_TOKEN
          value: v5ulT
        - name: PYTHONUNBUFFERED
          value: '1'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: bouncer-mqp
  labels:
    app: bouncer-mqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bouncer-mqp
  template:
    metadata:
      labels:
        app: bouncer-mqp
    spec:
      containers:
      - name: bouncer-mqp
        image: my_seeder
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["bouncer_mqp.py"]
        env:
        - name: MQ_HOST
          value: rabbitmq
        - name: API_URL
          value: http://seeder-api:8000
        - name: PYTHONUNBUFFERED
          value: '1'
