# https://github.com/helm/charts/tree/master/incubator/cassandra
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: cassandra
  namespace: kube-system
spec:
  chart: cassandra
  repo: https://kubernetes-charts-incubator.storage.googleapis.com/
  targetNamespace: default
  valuesContent: |-
    config:
      max_heap_size: 768M
      heap_new_size: 128M
      seed_size: 1
      num_tokens: 256
      cluster_size: 1
      dc_name: DC_1
      rack_name: RACK_1
      start_rpc: true
    env:
      JVM_OPS: $JVM_OPS -Djava.rmi.server.hostname=$POD_IP
    persistence:
      size: 3Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
