# https://github.com/helm/charts/tree/master/stable/elasticsearch
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  chart: stable/elasticsearch
  targetNamespace: default
  valuesContent: |-
    client:
      heapSize: 128m
      replicas: 1
    master:
      heapSize: 128m
      replicas: 2
      persistence:
        size: 2Gi
        accessMode: ReadWriteMany
    data:
      heapSize: 256m
      replicas: 1
      persistence:
        size: 2Gi
        accessMode: ReadWriteMany
