# https://github.com/helm/charts/tree/master/stable/filebeat
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: filebeat
  namespace: kube-system
spec:
  chart: stable/filebeat
  targetNamespace: default
  valuesContent: |-
    indexTemplateLoad:
      - elasticsearch-client:9200
    extraVars:
      - name: ELASTICSEARCH_HOST
        value: elasticsearch-client
      - name: ELASTICSEARCH_PORT
        value: "9200"
    config:
      output:
        file:
          enabled: false
        logstash:
          enabled: true
          hosts: ["logstash:5044"]
    filebeat:
      prospectors:
        - type: log
          enabled: true
          paths:
            - /var/log/*.log
            - /var/log/messages
            - /var/log/syslog
            - /var/log/containers/*.log
        - type: docker
          containers.ids:
          - "*"
          processors:
            - add_kubernetes_metadata:
                in_cluster: true
            - drop_event:
                when:
                  equals:
                    kubernetes.container.name: "filebeat"
