# https://github.com/helm/charts/tree/master/stable/filebeat
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: filebeat
  namespace: kube-system
spec:
  chart: stable/filebeat
  targetNamespace: default
  valuesContent: |-
    config:
      output:
        file:
          enabled: false
    filebeat:
      prospectors:
        - type: log
          enabled: true
          paths:
            - /var/log/*.log
            - /var/log/messages
            - /var/log/syslog
        - type: docker
          containers.ids:
          - "*"
          processors:
            - add_kubernetes_metadata:
                in_cluster: true
            - drop_event:
                when:
                  equals:
                    kubernetes.container.name: "filebeat"
    output:
      logstash:
        hosts: ["logstash:5044"]
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
