# https://medium.com/devopslinks/deploy-jenkins-helm-chart-on-k3s-running-on-macbook-484bb7ba588f
# https://github.com/helm/charts/tree/master/stable/jenkins
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: jenkins
  namespace: kube-system
spec:
  chart: stable/jenkins
  targetNamespace: default
  valuesContent: |-
    Master:
      UseSecurity: true
      AdminUser: jenkins
      AdminPassword: jenkins
    Persistence:
      Size: 1Gi
    rbac:
      install: true
