# https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-server-provisioner
  namespace: kube-system
spec:
  chart: stable/nfs-server-provisioner
  targetNamespace: default
  valuesContent: |-
    persistence:
      enabled: false
    storageClass:
      defaultClass: true
