# https://github.com/helm/charts/tree/master/stable/redis-ha
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: kube-system
spec:
  chart: stable/redis-ha
  targetNamespace: default
  valuesContent: |-
    fullnameOverride: redis
    image:
      tag: 5.0.4-alpine
    replicas: 3
    persistentVolume:
      size: 100Mi
